### ISSUE TITLE
【报错】请输入您所在的城市或城市+空格+地区（县） 

### ISSUE THREAD

**Issue by NealScx** [Kaguya233qwq/nonebot_plugin_kfcrazy#3]
![image](https://user-images.githubusercontent.com/85844254/201466939-c1894c1d-d7e7-4ffd-af36-527c9bfeb2d0.png)

```
11-12 16:56:12 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_kfcrazy) failed.
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.9/dist-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.9/dist-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 688, in simple_run
    await handler(
  File "/usr/local/lib/python3.9/dist-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_kfcrazy/__init__.py", line 222, in city_handler
    await KFC().get_city_id(city)
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_kfcrazy/__init__.py", line 68, in get_city_id
    district_name = city['districtName']
KeyError: 'districtName'

```

**Comment by Kaguya233qwq** [comment]
> 

问题已修复。请重新拉取项目或更新pip包

**Comment by Kaguya233qwq** [comment]
> ![image](https://user-images.githubusercontent.com/85844254/201466939-c1894c1d-d7e7-4ffd-af36-527c9bfeb2d0.png)
> 
> ```
> 11-12 16:56:12 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_kfcrazy) failed.
> Traceback (most recent call last):
>   File "/usr/local/bin/nb", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/nb_cli/commands/main.py", line 30, in run
>     run_bot(file, app)
>   File "/usr/local/lib/python3.9/dist-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
>     nonebot.run(app=f"{module_name}:{app}")
>   File "/usr/local/lib/python3.9/dist-packages/nonebot/__init__.py", line 273, in run
>     get_driver().run(*args, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/nonebot/drivers/fastapi.py", line 172, in run
>     uvicorn.run(
>   File "/usr/local/lib/python3.9/dist-packages/uvicorn/main.py", line 575, in run
>     server.run()
>   File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 60, in run
>     return asyncio.run(self.serve(sockets=sockets))
>   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 142, in _check_matcher
>     await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> > File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 186, in _run_matcher
>     await matcher.run(bot, event, state, stack, dependency_cache)
>   File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 716, in run
>     await self.simple_run(bot, event, state, stack, dependency_cache)
>   File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 688, in simple_run
>     await handler(
>   File "/usr/local/lib/python3.9/dist-packages/nonebot/dependencies/__init__.py", line 108, in __call__
>     return await cast(Callable[..., Awaitable[R]], self.call)(**values)
>   File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_kfcrazy/__init__.py", line 222, in city_handler
>     await KFC().get_city_id(city)
>   File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_kfcrazy/__init__.py", line 68, in get_city_id
>     district_name = city['districtName']
> KeyError: 'districtName'
> ```

问题已修复。请重新拉取项目或更新pip包
