### ISSUE TITLE
到菜单数据时就报错这个了

### ISSUE THREAD

**Issue by Laurc2004** [Kaguya233qwq/nonebot_plugin_kfcrazy#5]
Running Matcher(type='message', module=nonebot_plugin_kfcrazy) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/home/qbot/.venv/lib/python3.8/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/home/qbot/.venv/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 187, in run
    uvicorn.run(
  File "/home/qbot/.venv/lib/python3.8/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/home/qbot/.venv/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/qbot/.venv/lib/python3.8/site-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/home/qbot/.venv/lib/python3.8/site-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/qbot/.venv/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/qbot/.venv/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 707, in simple_run
    await handler(
  File "/home/qbot/.venv/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/qbot/.venv/lib/python3.8/site-packages/nonebot_plugin_kfcrazy/__init__.py", line 254, in store_handler
    menu_list, Food = await KFC().get_menu(store_id)
  File "/home/qbot/.venv/lib/python3.8/site-packages/nonebot_plugin_kfcrazy/__init__.py", line 158, in get_menu
    menu_detail = resp_json['data']['data']
KeyError: 'data'

**Comment by Kaguya233qwq** [comment]
当前肯德基小程序已进行更新，由于本人最近工作繁忙，本插件已长时间未维护。我将会在未来重构此插件，修复已知的问题并提升查询效率。
